# Generated by Django 4.0.4 on 2022-05-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
