# Generated by Django 4.0.4 on 2022-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stateapp', '0002_horse_delete_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='email',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='horse',
            name='name',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='horse',
            name='suggestion',
            field=models.CharField(default='', max_length=122),
        ),
    ]
