# Generated by Django 4.0.4 on 2022-05-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stateapp', '0003_horse_email_horse_name_horse_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='email',
            field=models.CharField(default='', max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(default='', max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='suggestion',
            field=models.CharField(default='', max_length=122, null=True),
        ),
    ]
