# Generated by Django 4.0.4 on 2022-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stateapp', '0006_alter_horse_fileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='fileimg',
            field=models.ImageField(default='', null=True, upload_to='static/cars'),
        ),
    ]
