# Generated by Django 4.0.4 on 2022-05-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stateapp', '0010_remove_horse_fileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='fileimg',
            field=models.ImageField(default='', null=True, upload_to='cars/'),
        ),
    ]
